name: internshala_go_india
description: "A new Flutter project."
#
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  dio: ^5.5.0+1
  flutter_dotenv: ^5.1.0
  google_fonts: ^6.2.0
  lottie: ^3.1.2
  weather_icons: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_native_splash: ^2.4.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  hive_generator: ^2.0.1


flutter_native_splash:
  background_image: "assets/images/bg1.jpg"
  android: true
  ios: true
  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - .env

  
